### ISSUE TITLE
For identifiserende felt så mangler beskrivelse av index feltet

### ISSUE THREAD

**Issue by torkjetil** [Altinn/docs#11]
https://altinn.github.io/docs/guides/tjenesteeier/grensesnitt-web-services/#prefill

PrefillIdentityFieldBE |  
-- | --
FieldValue | Verdi for identifiserende feltet. Må settes når det skal være mer enn ett preutfylt skjemasett for samme tjeneste og avgiver. Se avsnitt Identifiserende felter for mer info

Kobles index feltet opp til xpath uttrykk ? - ref Brukerveiledning TUL 7.2.8.2	Overstyrbare felter

Skulle gjerne også sette et eksempel på bruk og om dette kan brukes for å låse felter for endringer etter prefill gjennom rest API

**Comment by altinnadmin** [comment]
Hei,

Identifiserende felter benyttes for å unikt identifisere et sett med preutfyllingsdata som Altinn skal benytte ifbm. instansiering via [abonnement](https://altinn.github.io/docs/guides/tjenesteeier/grensesnitt-batch-til-altinn/#abonnement).

Ref. siste punkt [her](https://altinn.github.io/docs/guides/tjenesteeier/funksjonelle-scenario/#innsending-av-prefilldata):
> 2. Identifiserende felter
>    - Verdier som legges på et preutfylt skjemasett, for å gjøre skjemasettet unikt
>    - Verdiene kan være “hva som helst”, men typisk noe som kan knyttes til det preutfylte skjemasettet, f.eks. “rapport X”, “periode Y” (2 verdier).
>    - Preutfylte skjemasett uten identifiserende felter benyttes ved aktivisering av tjenester i Altinn portal, og/eller sammen med abonnement.
>    - Preutfylte skjemasett med identifiserende felter benyttes kun sammen med abonnement.

Egner seg mao. ikke som mekanisme for låsing av felter.

Men helt enig, det bør finnes noen eksempler på bruk av identifiserende felter i dokumentasjonen.
Jeg ser "Se avsnittet PunktOmIdentifiserendeFelter for mer informasjon" noen steder i doken, men virker som det avsnittet ikke eksisterer.

/cc: @ernstjonny
