### ISSUE TITLE
Søkemotor og lange ord

### ISSUE THREAD

**Issue by gnetrom** [Altinn/docs#12]
Søkemotor ikke helt god, spesielt på lange org.
F.eks: hvis man søker etter "AgencyDataExchange. SubmitOnlinePrefillPw", så må man legge til en whitespace etter siste bokstav (da finner den ordet, men highlighter den ikke), gjør en backspace (fjern whitespace), da blir ordet highlighted ... (frem og tilbake) ...

**Comment by altinnadmin** [comment]
Lukker denne da docs nå benytter elastic for søk.
