### ISSUE TITLE
Opprette tomt skjema for preutfylling gir 500-feil

### ISSUE THREAD

**Issue by Sigve-Fast** [Altinn/docs#195]
Prøver å opprette et tomt skjema som beskrevet her: https://altinn.github.io/docs/api/rest/meldinger/sende-inn/#post-for-å-opprette-preutfylt-skjema , men dette ender i en 500-feil uten noen info om hva som gikk galt. Henting av meldinger får jeg til. Hva gjør jeg galt?

```
const payload = 
{
    "Type": "FormTask",
    "ServiceCode": "4927",
    "ServiceEdition": 1,
    "_embedded": {
    }
};

fetch('https://www.altinn.no/api/my/messages?complete=false', {
    method: 'POST',
    credentials: 'include',
    headers: {
        'Content-Type': 'application/hal+json',
        'Accept': 'application/hal+json',
        'ApiKey': 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
    },
    body: JSON.stringify(payload) // body data type must match "Content-Type" header
})
```

**Comment by altinnadmin** [comment]
Hei @Sigve-Fast, kan du sjekke om det hjelper å gjøre kallet uten `"_embedded": { }` ?

**Comment by Sigve-Fast** [comment]
Samme feilen uten _embedded dessverre.

![image](https://user-images.githubusercontent.com/26789538/75860332-f2ce4400-5dfb-11ea-81f2-9c71cd1b8341.png)

![image](https://user-images.githubusercontent.com/26789538/75860890-d7176d80-5dfc-11ea-83ee-2fb7b5e1b2f0.png)

**Comment by altinnadmin** [comment]
Ok, takk, da må vi nok spørre vår API-guru om hjelp.
@erlendoksvoll Har du noen tanker om hvorfor dette feiler? 500 er jo veldig lite hjelpsomt...

**Comment by SandGrainOne** [comment]
Vi har identifisert en feil i kode relatert til dette. Vi vil lage en fiks umiddelbart, men det er dessverre ikke noen ny deploy før i midten av april.

**Comment by Sigve-Fast** [comment]
Takker :) Regner med det kommer ut på test ganske snart selv om prod lar vente på seg?

**Comment by altinnadmin** [comment]
> Vi har identifisert en feil i kode relatert til dette. Vi vil lage en fiks umiddelbart, men det er dessverre ikke noen ny deploy før i midten av april.

@SandGrainOne Regner med denne kan lukkes nå? :)

**Comment by SandGrainOne** [comment]
@altinnadmin Ja, dette ble fikset i aprilleveransen.
