### ISSUE TITLE
Laste ned XML-payload for skjema. Dokumentasjon utdatert?

### ISSUE THREAD

**Issue by Sigve-Fast** [Altinn/docs#196]
Prøver å følge dokumentasjonen her: https://altinn.github.io/docs/api/rest/meldinger/hente/#laste-ned-xml-payload-for-skjema-skjemadata for å hente ut xml'en til et skjema som ligger i innboksen. Følger lenkene dypere og ender til slutt opp med å følge en lenke på dette formatet: https://www.altinn.no/api/my/messages/a451669084/forms/195479306/formdata

Denne lenken skulle ifølge dokumentasjonen returnert en XML med formen `<Skjema>.....</Skjema>`. Det jeg derimot får returnert er en XML på formen: `<melding>....</melding>`. Har returverdien her endret seg eller misforstår jeg noe?

**Comment by SandGrainOne** [comment]
Nøyaktig innhold i en formdata payload vill variere basert på tjenesten det aktuelle elementet er knyttet til. Innholdet er bestemt av tjenesteeier som har definert dette ved hjelp av en XSD. Innholdet returnert av formdata endepunktet er altså det faktiske skjema med de data som er fylt ut.

De aller fleste skjema vil ha et rotelement med navn `Skjema` eller `melding`. I dette tilfelle ble det valgt å bruke `Skjema` som eksempel i dokumentasjonen. Dette kan sikkert gjøres tydeligere i dokumentasjonen. Holder derfor saken åpen.

**Comment by altinnadmin** [comment]
@Sigve-Fast Da er dok'en forbedret, takk for god feedback!

https://altinn.github.io/docs/api/rest/meldinger/hente/#laste-ned-xml-payload-for-skjema-skjemadata
