### ISSUE TITLE
[Haster] Chrome SameSite Updates

### ISSUE THREAD

**Issue by annesofie** [Altinn/docs#202]
Nylig begynte chrome å release sin nye versjon som gjør at det ikke lengre er mulig å kommunisere med Altinn fra nettlesere. **Vi lurer på om dere er i gang med en løsning på problemet? Og når evt. vil løsningen komme ut?**

Flere har allerede fått oppdateringen, så dette kommer til å bli et alvorlig problem når Chrome ruller endringen ut til flere.
For meg ser konsoll-advarselen slik ut
 
![altinn1](https://user-images.githubusercontent.com/6838310/75880501-b57aae00-5e1d-11ea-9f44-771584a29664.png)

I en test på en pc hvor det fortsatt fungerer kommer denne advarselen i konsollen:
 ![altinn2](https://user-images.githubusercontent.com/6838310/75880516-ba3f6200-5e1d-11ea-90cc-6f28922b3416.png)

En statusside om samesite-oppdateringen: https://www.chromium.org/updates/same-site

**Comment by altinnadmin** [comment]
Hei @annesofie, takk for feedback :)

Dette er en kjent problemstilling som vi jobber med der en del problemer allerede er fikset eller patchet, men noen saker er fortsatt åpne.

Jeg regner med at problemet du refererer til oppstår når en ekstern site benytter Altinn sine APIer klientside?

**Comment by annesofie** [comment]
Hei,

Takk for svar @altinnadmin. Ja det stemmer.

Vet du når dette vil være helt fikset? Det går ut over flere av våre tjenester. 

Anne Sofie

**Comment by altinnadmin** [comment]
@annesofie Vi planlegger å legge ut en fiks på mandag om det ikke dukker noe opp ifbm. test.

**Comment by altinnadmin** [comment]
@annesofie Da skal fiksen være i prod. Kan du teste at dette var riktig medisin for tjenestene deres?

**Comment by annesofie** [comment]
Hei! Ja, nå fungerer det. Tusen takk :)

**Comment by annesofie** [comment]
Hei igjen @altinnadmin! Nå ser det ut til at problemet har oppstått igjen, har dere en ide hvorfor? 

Anne Sofie

**Comment by altinnadmin** [comment]
@annesofie Ja, beklager, vi måtte rulle tilbake fiksen midlertidig pga. et problem relatert til vår integrasjon med ID-porten. En forbedret fiks er på vei, jeg gir deg beskjed når den er på plass i prod.

**Comment by RuXxar** [comment]
Har dere en offentlig nettside der dere legger ut denne type informasjon?
Det er ganske kritisk da det påvirker et stort antall brukere.

**Comment by altinnadmin** [comment]
> Har dere en offentlig nettside der dere legger ut denne type informasjon?
> Det er ganske kritisk da det påvirker et stort antall brukere.

Nei, dessverre. Vi har en [roadmap](https://altinn.github.io/docs/ny-funksjonalitet/roadmap/2020/), men den brukes for litt større planlagte endringer. I tillegg så er det en [side for driftsmeldinger](https://www.altinn.no/om-altinn/driftsmeldinger/), men den brukes for å varsle om mer "akutt trøbbel". Denne saken faller nok litt mellom disse to stolene...

Anyways, en oppdatert fiks er nå lagt ut i prod, så ting skal fungere igjen. @annesofie Kan du verifisere?

**Comment by HelgaJerven** [comment]
Hei!

Vi har fått følgende tilbakemelding i dag:

"Vi opplever fortsatt problemer. I går ettermiddag fungerte det fint, men i dag har både kundene våre og vi problemer med å logge på Altinn. Feilmeldingen vi får nå er: 
”Kommunikasjon med Altinn feilet. Status: 404 Melding: Message not found or access denied.” 

Vi får altså ikke logget på Altinn via Chrome, men det fungerer helt fint på Edge."

Dette skaper "akutt trøbbel" for svært mange brukere, så fint om dere kan legge ut driftsmeldinger om saken.

Mvh. Helga Jerven
Direktoratet for byggkvalitet

**Comment by altinnadmin** [comment]
Hei @HelgaJerven Når er det sitate over fra? Får du gjenskapt problemet nå i dag etter gårsdagens fiks?
Vi klarer pt. ikke å gjenskape, og ingen saker er kommet inn til service desk hos oss.

**Comment by TorOskar** [comment]
Ser ut som problemet oppstår på denne versjonen av Chrome:
Version 80.0.3987.132.
Tilbakemeldingene vi får er at det bare skjer på PROD ikke TT02. Jeg har ikke hatt noen problemer med denne versjonen på TT02.

**Comment by annesofie** [comment]
Hei,

Det fungerer igjen for oss i drift på e-Torg, men vi får veldig mange warnings.

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/6838310/76535702-92827680-647b-11ea-98f6-cc0ad29744c7.png)

**Comment by altinnadmin** [comment]
> Det fungerer igjen for oss i drift på e-Torg, men vi får veldig mange warnings.

Godt å høre at det fungerer! 👍

At det kommer noen warnings er som forventet da Altinn setter en del andre cookies som ikke er satt med `SameSite=None` og som ikke er nødvendige for at cross-site kommunikasjonen skal fungere. Ser også at det er liknende warnings relatert til andre sites i lista.

En ting jeg stusser litt over er at det virker som warning trigges for fire ulike "varianter" av URL for Altinn, både `http`og `https` samt med og uten `www`.

![image](https://user-images.githubusercontent.com/6088624/76605714-39fdb880-6511-11ea-96ec-cf8cf5e45a46.png)

Jeg mistenker at dette kan skyldes at du har noen gamle cookies lagret. Kunne du prøvd å slette alle varianter av cookies og se om antall varianter av altinn-relaterte warnings reduseres?

Alternativt så *kan* det bety at dere først gjør kall mot http som Altinn så redirecter til https, noe som er unødvendig og bør fikses.

**Comment by lurer** [comment]
Hei @altinnadmin,
Vi får de samme ulike cookies som Norkart får, med forskjellige variasjoner av URL og vi bruker https://www.altinn.no i våre kall.
![image](https://user-images.githubusercontent.com/5254730/76608686-5d773200-6516-11ea-8a80-6e6276f61b21.png)

**Comment by altinnadmin** [comment]
> Vi får de samme ulike cookies som Norkart får, med forskjellige variasjoner av URL og vi bruker https://www.altinn.no i våre kall.

Ok, takk Espen!

**Comment by altinnadmin** [comment]
@annesofie @lurer Da har vi diskutert dette og warnings er som forventet og at det skyldes noen mindre viktige cookies som pt. ikke settes med secure eller samesite.

@HelgaJerven Kan du bekrefte at ting fungerer nå også hos dere?

**Comment by HelgaJerven** [comment]
Hei!
Det er Holte som har meldt inn feilen til meg og Tor Oskar, og som sitatet over var hentet fra. Jeg har bedt dem om å kommentere i tråden om de fortsatt opplever feil :)

**Comment by altinnadmin** [comment]
Da oppfatter jeg at ting fungerer for alle parter, så jeg lukker denne. Igjen, takk for feedback!

**Comment by HelgaJerven** [comment]
Takk for god hjelp!
