### ISSUE TITLE
Må man logge inn med virksomhetssertifikat for å opprette virksomhetsbruker? - Er lenken som beskriver hvordan virksomhetsbruker opprettes riktig

### ISSUE THREAD

**Issue by aberner** [Altinn/docs#29]
På denne siden:
https://altinn.github.io/docs/api/sluttbruker/autentisering/virksomhetssertifikat/

 så står det følgende:

> Etter at man har installert sertifikat fra utsteder, må man registrere sertifikatet i Altinn og opprette en såkalt virksomhetsbruker. Dette er beskrevet her.

Her har lenken: https://www.altinn.no/hjelp/innlogging/alternativ-innlogging-i-altinn/

Jeg blir usikker på om det faktisk er et krav om å logge på med virksomhetssertifikat i nettleseren for å komme inn å opprette en virksomhetsbruker. Er dette riktig?

Burde ikke lenken gått til: 
https://www.altinn.no/hjelp/innlogging/alternativ-innlogging-i-altinn/virksomhetssertifikat/

I teksten her står det:  "Kan gjøres på to måter, enten ved innlogging eller under Profil."

- Dette antyder at det bør være mulig å opprette en virksomhetsbruker uten å måtte gå via den litt tunge prosessen med å logge på med et virksomhetssertifikat i nettleser.
(Vi ønsker i utgangspunktet ikke at virksomhetssertifikatet må installeres i noe nettleser.)

Fint om dere presiserer hva som er nødvendig prosess for å opprette en virksomhetsbruker.

**Comment by erlendoksvoll** [comment]
Hei!

Det stemmer at det er to varianter som begge kan brukes. Om man ikke ønsker å opprette virksomhetsbruker fra samme maskin som sertifikatet ligger på kan man eksportere public og opprette fra virksomhetens profil. Skal legge til det som alternativ på docs også.

Erlend
