### ISSUE TITLE
Ødelagt link i docs/content/api/rest/meldinger/sende-inn.md

### ISSUE THREAD

**Issue by AndreasEike** [Altinn/docs#301]
Hei, linken på linje 19 i docs/content/api/rest/meldinger/sende-inn.md ("metadata ressursen") er ødelagt. Skulle gjerne vite hvilken side denne peker til.

**Comment by AndreasEike** [comment]
I den interaktive dokumentasjonen her: https://altinn.github.io/docs/api/rest/meldinger/sende-inn/ linkes det til https://altinn.github.io/docs/api/rest/diverse/metadata, men denne virker ikke. 
<img width="1436" alt="Skjermbilde 2021-03-01 kl  14 37 34" src="https://user-images.githubusercontent.com/46325452/109504287-add6ff00-7a9b-11eb-926a-a7a5248f720d.png">

**Comment by SandGrainOne** [comment]
Det skulle antagelig være linket til
https://altinn.github.io/docs/api/rest/metadata/#hente-metadata-for-enkelt-tjeneste

**Comment by SandGrainOne** [comment]
Har nå fikset denne og et par andre linker.

**Comment by altinnadmin** [comment]
Takk for at du sier fra @AndreasEike! 👍
