### ISSUE TITLE
Vag referanse til kapittler

### ISSUE THREAD

**Issue by AndreasEike** [Altinn/docs#303]
Ser i dokumentet "docs/content/api/soap/funksjonelle-scenario/_index.md" at det gjentatte ganger refereres til kapittelnummer. I og med at dokumentasjonen ikke bruker kapittelnummer fast, gjør at det er vanskelig å finne det tilsvarende kapittelet i dokumentasjonen. Burde kanskje bruke hyperlinker til dokumentene istedet.

**Comment by SandGrainOne** [comment]
En del av dokumentasjonen var opprinnelig et word dokument som ble konvertert til Markdown. Det er dessverre en del rester igjen etter det.

**Comment by AndreasEike** [comment]
Skjønner, vet noen hvilke deler av dokumentasjonen disse numrene refererer til?

**Comment by altinnadmin** [comment]
@HanneLauritsen1967 @lvbachmann  Se spørsmål over fra @AndreasEike.
Klarer vi å grave fram den eldgamle Word-versjonen av API-dokumentasjonen for Altinn II? Denne var vel tilgjengelig via Altinnett og altinn.brreg.no i sin tid...

**Comment by lvbachmann** [comment]
@AndreasEike Jeg har funnet en gammel versjon av dokumentet som var grunnlag for denne delen av dokumetasjonen:
[Implementasjonsguide for sluttbrukersystemer.pdf](https://github.com/Altinn/docs/files/6263267/Accenture.Altinn.Implementasjonsguide.for.sluttbrukersystemer.pdf)

Ved et raskt blikk, ser det ut som at kapittelnummereringen stemmer med referansene, men jeg tør ikke garantere at det er 100 % treff.

cc: @HanneLauritsen1967 @altinnadmin

**Comment by lvbachmann** [comment]
Rettet med #355
