### ISSUE TITLE
AltinnContextMapper

### ISSUE THREAD

**Issue by TorOskar** [Altinn/docs#31]
Hei, 

Kommentar til 
https://altinn.github.io/docs/guides/tul/vedlegg/g/
seksjon "Bruk av AltinnMapperContext", "Funksjonaliteten ved bruk av AltinnMapperContext fungerer ikke ved SBS-innsending"

Tror det var i 17.1 eller 17.2 at vi fikk tilgang til AltinnContextMapper innsendinger over REST API i alle fall.

Hilsen,
Tor Oskar

**Comment by altinnadmin** [comment]
@TorOskar Stemmer, ble fikset i 17.1 for både REST og WS: https://altinn.github.io/docs/releases/2017/17-1/#altinnmappercontext-for-sbs-rest-innsendinger-20468
