### ISSUE TITLE
Oppgitt endepunkt er feil på NotificationAgencyExternal

### ISSUE THREAD

**Issue by sivaglen** [Altinn/docs#33]
Endepunkt oppgitt under NotificationAgencyExternal på https://altinn.github.io/docs/guides/integrasjon/tjenesteeiere/webservice/#archivecommon-1 funker ikke (mangler en "/")

**Comment by altinnadmin** [comment]
@ernstjonny , kan du fikse denne? Gjelder alle tre URL'ene under NotificationAgencyExternal.
