### ISSUE TITLE
Feil underkategori dukker opp når jeg trykker "Vedlegg".

### ISSUE THREAD

**Issue by andreas-didriksen** [Altinn/docs#335]
https://altinn.github.io/docs/altinn-studio/app-creation/data/

Når jeg går inn på  "data" -> "Vedlegg" så endres undermenyen til venstre til underkategoriene som tilhører Utviklingsguider. 
Jeg opplever ikke denne feilen når cloner docs repoet og kjører det lokalt.

![image](https://user-images.githubusercontent.com/75472603/113841757-56126e80-9792-11eb-8cb8-d8db220b1b55.png)

![image](https://user-images.githubusercontent.com/75472603/113841881-78a48780-9792-11eb-846d-90a9e5c2a956.png)

**Comment by altinnadmin** [comment]
Takk! Denne issuen var akkurat det jeg trengte for å bruke noen minutter til å ta en kikk på dette problemet (som over tid har dukket opp tilfeldig i ulike deler av menyen).

Det virker som det er en bug som er [fikset upstream for mange år siden i Matcornic Learn](https://github.com/matcornic/hugo-theme-learn/pull/105).

Jeg backporter fiksen, så får vi se om det hjelper :)

FYI @Febakke

**Comment by andreas-didriksen** [comment]
Lignende feil når jeg går inn på Konfigurasjon - Prosess og velger Automatisk sletting. Det som skjer her, er at undermenyene bare lukkes.  Er det samme feil eller skal jeg lage en ny issue?

![image](https://user-images.githubusercontent.com/75472603/113866183-4bb19e00-97ad-11eb-8586-de50dd2f6d11.png)

**Comment by altinnadmin** [comment]
Er nok samme feil. Vent til jeg har pushet fiks før du ev. lager ny issue.

**Comment by altinnadmin** [comment]
@andreas-didriksen Virker som dette var riktig medisin. Klarer ikke å trigge denne feilen nå.
