### ISSUE TITLE
Filtrering av resultat

### ISSUE THREAD

**Issue by fiLLLip** [Altinn/docs#40]
https://github.com/Altinn/docs/blob/master/content/guides/integrasjon/sluttbrukere/api/meldinger/hente.md

Ønsker en mer detaljer beskrivelse på hvordan resultatene kan filtreres. Spesifikke scenario:

- Ved bruk av fler enn ett filter, `ServiceOwner` og `ServiceCode`
- `CreatedDate`/`LastChangedDateTime` større enn / mindre enn spesifikk dato. For eksempel hente ut for hele januar

**Comment by fiLLLip** [comment]
@erlendoksvoll Nydelig 👍

**Comment by erlendoksvoll** [comment]
For fremtidig referanse: https://altinn.github.io/docs/guides/integrasjon/sluttbrukere/api/meldinger/hente/#filtrering
