### ISSUE TITLE
SandBox

### ISSUE THREAD

**Issue by djefimov** [Altinn/docs#50]
Hi guys,

Is there a sandbox or any kind of a test environment  or test account to setup and play with your api?

regards

**Comment by altinnadmin** [comment]
Hi @djefimov,

Yes, we have test environments and test users, but you need to mail us two forms to trigger the process to get access. This process is unfortunately not yet "self-serviced", but that's one of our goals for the future.

Here's a [google translation of the "getting-started docs"](https://translate.google.no/translate?sl=no&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Faltinn.github.io%2Fdocs%2Fguides%2Fintegrasjon%2Fsluttbrukere%2Fapi%2Fkom-i-gang%2F&edit-text=) with the details and links to the forms (which are word documents).

/cc: @erlendoksvoll
