### ISSUE TITLE
URL for InfoPath webservice 

### ISSUE THREAD

**Issue by TorOskar** [Altinn/docs#51]
Hei, 

Tror URLen for ReporteeElementListInfoPath tjenesten skal være
http://infopathservices.altinn.no:87/serviceengine/ReporteeElementListInfoPath.svc?WSDL
ikke
https://mapperservices.altinn.no:87/ServiceEngine/ReporteeElementListInfoPath.svc?WSDL
på siden
https://altinn.github.io/docs/guides/tul/vedlegg/g/

Hilsen,
Tor Oskar

**Comment by altinnadmin** [comment]
Ah, stemmer, er nå fikset. Takk!
