### ISSUE TITLE
Go from SOAP to REST

### ISSUE THREAD

**Issue by ollyde** [Altinn/docs#528]
### Description

As title.

SOAP makes it difficult for non Microsoft tech stack users, we are using Rust personally, and honestly I though SOAP died in the 2000s, it's strange choice to use for a public API.

**Comment by SandGrainOne** [comment]
There are already REST alternatives to most features. SOAP still exists for backwards compatibility and for Tax. 

Could you explain what type of operations you need to perform?

**Comment by ollyde** [comment]
@SandGrainOne no problem, thanks for the response. We are using using mainly Tender portal APIs.
