### ISSUE TITLE
xpath i feilmeldinger fra validering i rest

### ISSUE THREAD

**Issue by torkjetil** [Altinn/docs#57]
Skulle gjerne sett et eksempel her https://altinn.github.io/docs/guides/integrasjon/sluttbrukere/api/meldinger/validere/ som viser xpath(https://altinn.github.io/docs/releases/2018/18-4/#xpath-i-feilmeldinger-fra-validering-i-rest-grensesnittet) til feltet det er feil på. Kan se ut som det er fieldname? men ikke godt å se med slike eksempeldata

**Comment by altinnadmin** [comment]
Ser den. Tror det er et nytt "Xpath"-felt som benyttes. @steriasvendsen, kan du oppdatere doken med et korrekt eksempel?

**Comment by altinnadmin** [comment]
@torkjetil Da er PR merget og dok'en er oppdatert:
https://altinn.github.io/docs/guides/integrasjon/sluttbrukere/api/meldinger/validere/
