### ISSUE TITLE
Postnummer og -sted

### ISSUE THREAD

**Issue by havardge** [Altinn/docs#6]
Er det mulig å hente postnummer og -sted fra APIet?

**Comment by erlendoksvoll** [comment]
Hei!

Man kan hente ut dette for innlogget bruker i api/my/profile.

For virksomheter er dette foreløpig ikke inkludert i /api/orgnr/profile, så det er bare mulig å hente ut via tjenesteeier-apiet.

Erlend

**Comment by altinnadmin** [comment]
Ref. https://altinn.github.io/docs/api/sluttbruker/diverse/profil/
