### ISSUE TITLE
Webapp eksempel

### ISSUE THREAD

**Issue by havardge** [Altinn/docs#7]
For iOS / Android bruker man innebygd nettleser for å hente ut cookien .ASPXAUTH. Hvordan løser man dette med Webapps? Da har man jo ikke denne muligheten.

Kan det gjøres backend? Frontend?

**Comment by erlendoksvoll** [comment]
Hei

Om man lager en nettside som kaller api-et vil denne ha cookien tilgjengelig med [withCredentials satt til true](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials) - husk også crossDomain. :)

Dette kan også gjøres backend, dersom man autentiserer seg med virksomhetssertifikat eller brukernavn/passord. Merk at dette ikke vil si at man kan ha bruker som logger inn i nettleser for deretter å håndtere kommunikasjonen med Altinn på vegne av bruker fra backend. Det vil i så fall være en ren systemintegrasjon.

**Comment by havardge** [comment]
Hei,

vi har allerede forsøkt dette, men vi får svaret:

_Failed to load https://tt02.altinn.no/api/my/messages: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.xxxxxxxxx.no' is therefore not allowed access. The response had HTTP status code 400._

```
$.ajax({
    url: "https://tt02.altinn.no/api/my/messages",
    method: "GET",
    crossDomain: true,
    headers: {
      "X-Requested-With": "XMLHttpRequest",
        "ApiKey": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
        "Accept": "application/hal+json",
        "Content-Type": "application/hal+json"
      },
      xhrFields: {
        withCredentials: true
      }
  })
  .done(function(data) {
    console.log(data);
  })

```

**Comment by altinnadmin** [comment]
@havardge Har dere [registrert applikasjonen](https://altinn.github.io/docs/api/sluttbruker/kom-i-gang/#registrer-din-applikasjon)? Kan virke som det er manglende [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) som er problemet?

**Comment by havardge** [comment]
Hei igjen, ja den skal være registrert. Det har vært litt krøll med registreringen tror jeg. Fordi URL ble satt feil i starten. Er det mulig at domeneeier kan sjekke hvilke URLer som er registrert?

**Comment by altinnadmin** [comment]
Nei, dessverre så er det foreløpig ikke mulig for domeneeier selv å sjekke hvilke URLer som er registrert.

Har nå oppdatert doken med hvordan man med script kan [verifisere at et domene (origin) er satt opp](https://altinn.github.io/docs/api/sluttbruker/kom-i-gang/#cross-origin-resource-sharing-cors), men det er kun en **bekreftelse** på at CORS er satt opp mot et gitt domene. Men hvis du har noen ulike "krøll-kandidater" så kan du i det minste sjekke dem...
