### ISSUE TITLE
Sporvalg

### ISSUE THREAD

**Issue by xmrsa** [Altinn/docs#70]
Jeg savner en teknisk beskrivelse av Sporvalg under https://altinn.github.io/docs/guides/tul/funksjonalitet/.

Jeg har slitt med å få sporvalgene mine til å fungere fordi det ikke er et enkelt svar i skjemaet som avgjør hvilket sporvalg man skal velge. F.eks. vil endringer i et beløpsfelt i skjemaet fører til at andre betingelser sjekkes og at et eget sporvalgsfelt /melding/@my:sporvalgNaering får en verdi.

Er det da slik at jeg må ha Alltid-posting på BÅDE beløpsfeltet og @my:sporvalgNaering, og er det beløpsfeltet og/eller @my:sporvalgNaering som skal ha NotifyHost-kode knyttet til seg?
Sporvalgene er også avhengig av om man har én eller flere virksomheter i foretaket og hvilken næring foretaket driver i. Se vedlagt sporvalg. Den siste siden "Kommentarfelt og kontaktperson" skal alltid vises og har dermed fått en tullebetingelse.

![sporvalgeksempel](https://user-images.githubusercontent.com/42466346/44260430-a40a8a80-a214-11e8-9d63-5d7b4af33116.PNG)

Jeg har også fått erfare at om jeg har lagt til en visning av sporvalgsfeltene på den første siden i skjemaet (for lett å kunne holde oversikten over valgt spor under utviklingen) så vil ikke disse feltene komme med på nedtrekkslisten på senere sider i skjemaet, selv om de også er lagt på disse sidene. Jeg måtte derfor være nøye med å vise sporvalgsverdiene som UTTRYKKSBOKSER på sider der de ikke var i direkte bruk.

Det er ikke vanskelig å sette opp et sporvalg med kun ett innledende Ja/Nei-spørsmål på første side. Jeg hadde ønsket meg et litt mer komplisert eksempel også.

**Comment by altinnadmin** [comment]
Hei,

Jeg oppfatter at konfigurasjon for å alltid poste (samt kode) skal settes på beløpsfelt (altså de felter som påvirker generering av hjelpefelt som du så benytter for sporvalg).

https://altinn.github.io/docs/guides/tul/tjenestetyper/innsending/#sporvalg
https://altinn.github.io/docs/guides/tul/vedlegg/a/#sporvalg

Kompliserte sporvalg kan dessverre være utfordrende å sette opp i dagens løsningen, og det er definitivt noe vi må forbedre med [3.0](https://altinn.github.io/docs/altinncore/).
