### ISSUE TITLE
Finner ikke skjema "Tilgang til Altinns utviklingsmiljø AI-DEV" i selvbetjeningsportal

### ISSUE THREAD

**Issue by TorOskar** [Altinn/docs#8]
Skjema "Tilgang til Altinns utviklingsmiljø AI-DEV" er referert til på siden 
https://altinn.github.io/docs/guides/mapperutvikling/prosessen/
men jeg finner ikke skjemaet i portalen.

Hilsen,
Tor Oskar

**Comment by erlendoksvoll** [comment]
Skjemaet skal ligge under tilganger - har oppdatert beskrivelsen med mer info for å tydeliggjøre hvor de finnes :)

Erlend
