### ISSUE TITLE
Notification i PreFill

### ISSUE THREAD

**Issue by TorOskar** [Altinn/docs#80]
Hei, 

Kommentar til denne delen:
https://altinn.github.io/docs/guides/integrasjon/tjenesteeiere/webservice/#notification

Jeg har jobbet med notification i preFill. Fant at jeg måtte legge ved 

> NotifyType | Skal ikke fylles ut av tjenesteeier. Brukes internt i Altinn.

for at kallet skulle gå gjennom i TT02.

Uten dette fikk jeg:
-		exception	{"Det oppstod en feil ved forsøk på å serialisere parameteren http://www.altinn.no/services/ServiceEngine/PreFill/2009/10:preFillFormTask. InnerException-meldingen var Nummereringsverdien 0 er ugyldig for typen KommIT.FIKS.AdapterAltinnSvarUt.Services.WS.AltinnPreFill.NotificationType og kan ikke serialiseres. Kontroller at nødvendige nummereringsverdier finnes og er merket med attributtet EnumMemberAttribute hvis typen har attributtet DataContractAttribute.. Se InnerException hvis du vil ha detaljer."}	System.Exception {System.ServiceModel.CommunicationException}

Koden min ble da slik:
` var notification = new WS.AltinnPreFill.Notification
                {
                    LanguageCode = "1044",
                    NotificationType = "DIBK_flex1st_email_sms",
                    NotifyType = NotificationType.PreFill,
                    ShipmentDateTime = DateTime.Now,
                    TextTokens = new TextTokenSubstitutionBEList()
                {
              `
Virker som enten dokumentasjon eller WS er feil her.

Hilsen,
Tor Oskar

**Comment by ernstjonny** [comment]
Hei

NotifyType er en intern entitet som ikke er ment å skulle fylles ut av tjenesteeier. Det er beklagelig at den er eksponert i det eksterne grensesnittet, men slik er det i dag. 

Årsaken til at kallet ikke gikk igjennom uten at NotifyType var fylt ut kan jeg ikke svare på. Jeg har forsøkt å sende inn uten å kunne gjenskape feilen.
